export const quizData = [
  // ===== ドメイン1: 生成AIの基礎 (1-25) =====
  {
    id: 1, domain: "生成AIの基礎",
    question: "開発チームが複雑な数学的問題を解決するためのアプリケーションを構築しています。Zero-shotプロンプティングではモデルが計算ミスを繰り返すため、思考プロセスをステップバイステップで出力させる必要があります。最も適切なプロンプト手法はどれですか？",
    choices: ["Few-shot prompting", "Chain-of-Thought (CoT) prompting", "Meta-prompting", "Directional-stimulus prompting"],
    correct: 1,
    explanation: "CoTは推論過程をステップごとに書き出させることで論理的精度を高める手法です。複雑な計算や推論タスクに特に有効です。",
  },
  {
    id: 2, domain: "生成AIの基礎",
    question: "Amazon Bedrockにおいて、極めて高いスループットとミリ秒単位の応答が求められる単純な意図分類タスクに最適な、最もコスト効率の高いモデルはどれですか？",
    choices: ["Claude 3.5 Sonnet", "Claude 3 Haiku", "Llama 3 70B", "Mistral Large"],
    correct: 1,
    explanation: "Claude 3 HaikuはClaudeファミリー中最も速く・安く、単純タスクに最適です。Sonnetはバランス型、Opusは最高性能です。",
  },
  {
    id: 3, domain: "生成AIの基礎",
    question: "テキストデータから意味的な類似性を計算するために、多次元のベクトル空間に変換するプロセスを何と呼びますか？",
    choices: ["Tokenization", "Embedding", "Normalization", "Quantization"],
    correct: 1,
    explanation: "Embeddingはテキストを数値ベクトルに変換し、コサイン類似度などで意味的な近さを計算できます。RAGの中核技術です。",
  },
  {
    id: 4, domain: "生成AIの基礎",
    question: "画像生成モデルにおいて、生成された画像の一部を編集し、周囲の文脈に合わせた新しい要素を追加する手法はどれですか？",
    choices: ["Outpainting", "Inpainting", "Style Transfer", "Text-to-Image"],
    correct: 1,
    explanation: "Inpaintingは画像の内側の指定領域を文脈に合わせて修正・追加します。Outpaintingは画像の外側を拡張する手法です。",
  },
  {
    id: 5, domain: "生成AIの基礎",
    question: "トークナイザーが「unhappiness」という単語を「un」「happi」「ness」のように分割する場合、このトークン化手法は何に分類されますか？",
    choices: ["Word-level tokenization", "Character-level tokenization", "Subword-level tokenization (BPE/WordPiece)", "Sentence-level tokenization"],
    correct: 2,
    explanation: "BPEやWordPieceなどのサブワード分割は、未知語対策と語彙サイズのバランスを保つ現代的なトークン化手法です。",
  },
  {
    id: 6, domain: "生成AIの基礎",
    question: "ハルシネーションを抑制するために、モデルが回答を生成する前に信頼できるソースから情報を検索し、それをプロンプトに組み込むアーキテクチャを何と呼びますか？",
    choices: ["Fine-tuning", "RLHF", "RAG (Retrieval-Augmented Generation)", "Chain-of-Thought"],
    correct: 2,
    explanation: "RAGは外部の信頼できるデータソースを検索してコンテキストに組み込むことで、ハルシネーションを大幅に抑制できます。",
  },
  {
    id: 7, domain: "生成AIの基礎",
    question: "モデルが「プロンプトインジェクション」攻撃を受け、システムプロンプトの制限を無視して機密情報を出力するリスクがあります。これを防ぐための最も効果的なAWSマネージドサービスはどれですか？",
    choices: ["Amazon GuardDuty", "Amazon Bedrock Guardrails", "AWS WAF (標準設定)", "Amazon Inspector"],
    correct: 1,
    explanation: "Bedrock Guardrailsはプロンプトインジェクションや有害コンテンツのフィルタリングを行うAWSのベストプラクティスです。",
  },
  {
    id: 8, domain: "生成AIの基礎",
    question: "Amazon Bedrockにおいて、モデルが次のトークンを選択する際、累積確率が特定のしきい値に達するまでの上位候補から選択するパラメータはどれですか？",
    choices: ["Temperature", "Top-K", "Top-P (Nucleus Sampling)", "Stop sequences"],
    correct: 2,
    explanation: "Top-P（ nucleus sampling）は累積確率がしきい値に達するまでの候補からサンプリングします。Top-Kは上位K個から選択します。",
  },
  {
    id: 9, domain: "生成AIの基礎",
    question: "モデルが学習時に使用したデータセットに含まれない、最新のニュースや株価情報を回答させるための最適な方法はどれですか？",
    choices: ["モデルを毎日再学習させる", "大規模なコンテキストウィンドウを持つモデルにすべてのニュースを流し込む", "Amazon Bedrock Agentsを使用してリアルタイム検索ツールと連携する", "モデルのTemperatureを最大にする"],
    correct: 2,
    explanation: "Bedrock AgentsでリアルタイムAPIや検索エンジンと連携するのが最も効率的で、モデルの再学習は不要です。",
  },
  {
    id: 10, domain: "生成AIの基礎",
    question: "基盤モデル（Foundation Model）の「知識のカットオフ」とは何を指しますか？",
    choices: ["モデルが一度に出力できる最大トークン数", "モデルのトレーニングデータが収集された最後の日付", "モデルが処理できるコンテキストウィンドウのサイズ", "推論時に課金が停止される時間制限"],
    correct: 1,
    explanation: "知識のカットオフはトレーニングデータの収集終了日であり、それ以降の情報はモデルが知らないためRAGやAgentsで補完します。",
  },
  {
    id: 11, domain: "生成AIの基礎",
    question: "マルチモーダルモデルの主な特徴は何ですか？",
    choices: ["複数の異なるプログラミング言語を同時に生成できること", "テキスト、画像、音声など、異なる種類のデータを単一のモデルで処理できること", "複数のAWSリージョンで同時に稼働すること", "複数のユーザーが同時にアクセスできること"],
    correct: 1,
    explanation: "マルチモーダルモデルはテキスト・画像・音声などの異なるモダリティを統合的に処理できます。Claude 3はその代表例です。",
  },
  {
    id: 12, domain: "生成AIの基礎",
    question: "トークン化において、辞書にない単語（OOV）が発生した場合の一般的な対処法はどれですか？",
    choices: ["単語を無視して削除する", "単語を未知のトークン（[UNK]）に置き換える、またはサブワードに分割する", "エラーを返して処理を中断する", "ランダムな単語に置き換える"],
    correct: 1,
    explanation: "現代のトークナイザーはOOVをサブワード分割（BPE等）で対処するか、[UNK]トークンで表現します。",
  },
  {
    id: 13, domain: "生成AIの基礎",
    question: "Claude 3.5 Sonnetのコンテキストウィンドウが200kトークンである場合、これは何を意味しますか？",
    choices: ["20万文字の回答を生成できること", "入力プロンプトと出力回答の合計として20万トークンまで処理できること", "1秒間に20万リクエストを処理できること", "20万個のパラメータを持っていること"],
    correct: 1,
    explanation: "コンテキストウィンドウは入力+出力の合計トークン数の上限です。200kトークンは長い文書の処理に非常に有利です。",
  },
  {
    id: 14, domain: "生成AIの基礎",
    question: "プロンプトエンジニアリングにおいて、回答のフォーマットをJSON形式に固定したい場合に最も効果的な方法はどれですか？",
    choices: ["「JSONで答えてください」と1回だけ書く", "Few-shotプロンプトでJSON形式の例示を複数提供し、スキーマを明示する", "モデルのTemperatureを0にする", "ストリーミングを無効にする"],
    correct: 1,
    explanation: "具体的なJSONスキーマの例示（Few-shot）とスキーマの明示が出力フォーマット制御に最も効果的です。",
  },
  {
    id: 15, domain: "生成AIの基礎",
    question: "自律的なエージェントを設計する際、思考、行動、観察を繰り返すループを何と呼びますか？",
    choices: ["ReAct (Reasoning and Acting)", "RLHF", "Backpropagation", "Gradient Descent"],
    correct: 0,
    explanation: "ReActは推論（Reason）と行動（Act）を組み合わせるエージェントの基本フレームワークです。Bedrock Agentsで採用されています。",
  },
  {
    id: 16, domain: "生成AIの基礎",
    question: "Stable Diffusionのような拡散モデル（Diffusion Model）が画像を生成する仕組みはどれですか？",
    choices: ["既存の画像を切り貼りする", "ノイズから始まり、ステップごとにノイズを除去して画像を構築する", "ピクセルをランダムに配置する", "テキストをそのまま画像データに変換する"],
    correct: 1,
    explanation: "拡散モデルはランダムノイズから始まり、逆拡散プロセスで徐々にノイズを除去して高品質な画像を生成します。",
  },
  {
    id: 17, domain: "生成AIの基礎",
    question: "Amazon Titan Text Embeddings v2を使用する際、出力されるベクトルの次元数（Dimensions）を増やすと一般的にどうなりますか？",
    choices: ["検索精度が向上する可能性があるが、計算コストとストレージ容量が増える", "検索精度が低下する", "推論速度が速くなる", "コストが安くなる"],
    correct: 0,
    explanation: "次元数を増やすと表現力・精度が向上する可能性がありますが、ストレージと計算コストが増加します。Matryoshka Embeddingsで調整可能です。",
  },
  {
    id: 18, domain: "生成AIの基礎",
    question: "モデルが特定の単語やフレーズを生成しないように制御する最も簡単な方法はどれですか？",
    choices: ["フルファインチューニング", "Stop sequences (停止シーケンス) の設定", "VPCエンドポイントの使用", "リージョンの変更"],
    correct: 1,
    explanation: "Stop sequencesは指定した文字列が出力された時点で生成を停止します。特定フレーズの除外にも活用できます。",
  },
  {
    id: 19, domain: "生成AIの基礎",
    question: "プロンプトの最後に「ステップバイステップで考えてみましょう」と付け加える手法は、どのテクニックの典型例ですか？",
    choices: ["Few-shot", "Zero-shot CoT", "Role prompting", "Self-consistency"],
    correct: 1,
    explanation: "「ステップバイステップで」という一言を追加するだけでCoTを誘発するZero-shot CoTは、例示なしで推論精度を向上させます。",
  },
  {
    id: 20, domain: "生成AIの基礎",
    question: "基盤モデルを特定のタスク（例：特定の業界のQ&A）に特化させるために、比較的少量のラベル付きデータで調整することを何と呼びますか？",
    choices: ["Pre-training", "Fine-tuning", "Quantization", "Distillation"],
    correct: 1,
    explanation: "Fine-tuningは少量のタスク固有データでモデルを調整し、特定ドメインでの性能を向上させます。RAGとの使い分けが重要です。",
  },
  {
    id: 21, domain: "生成AIの基礎",
    question: "生成AIにおける「アテンション・メカニズム（Attention Mechanism）」の役割は何ですか？",
    choices: ["GPUのメモリ消費を抑えること", "入力シーケンス内の各要素の重要度を動的に重み付けし、関連性の高い情報を強調すること", "ユーザーの入力をフィルタリングすること", "モデルのパラメータをゼロにすること"],
    correct: 1,
    explanation: "アテンション機構はトランスフォーマーの中核で、文中の各単語が他の単語に対してどれだけ「注目」するかを動的に計算します。",
  },
  {
    id: 22, domain: "生成AIの基礎",
    question: "Amazon Bedrockでモデルを選択する際、「スループット（Throughput）」とは何を測定するものですか？",
    choices: ["モデルの学習時間", "単位時間あたりに処理できるトークン数やリクエスト数", "モデルの重みのファイルサイズ", "ベクトルDBの容量"],
    correct: 1,
    explanation: "スループットは単位時間あたりの処理能力を示します。高トラフィックのアプリではProvisioned Throughputで保証する必要があります。",
  },
  {
    id: 23, domain: "生成AIの基礎",
    question: "「Temperature」パラメータを 0 に設定した場合の挙動として正しいものはどれですか？",
    choices: ["回答が最もランダムで創造的になる", "常に最も確率の高いトークンが選択され、決定論的な回答になる", "回答が生成されなくなる", "入力プロンプトが無視される"],
    correct: 1,
    explanation: "Temperature=0では最高確率のトークンのみを選択するため、同じ入力に対して常に同じ出力が得られます。コード生成や事実確認に適しています。",
  },
  {
    id: 24, domain: "生成AIの基礎",
    question: "LLMにおいて「パラメータ数」が多いことは、一般的に何を意味しますか？",
    choices: ["モデルがより複雑なパターンを学習できる可能性があるが、推論に多くのリソースを必要とする", "モデルが常に正確であることを保証する", "モデルが無料で利用できる", "モデルがオフラインで動作する"],
    correct: 0,
    explanation: "パラメータ数は表現力に影響しますが、推論コスト・メモリも増加します。タスクに応じた適切なサイズのモデル選択が重要です。",
  },
  {
    id: 25, domain: "生成AIの基礎",
    question: "画像生成における「ネガティブプロンプト（Negative Prompt）」の用途は何ですか？",
    choices: ["生成したいものを強調する", "生成画像に含めたくない要素（例：「低品質」「余分な指」）を指定する", "モデルの学習を停止する", "画像を白黒にする"],
    correct: 1,
    explanation: "ネガティブプロンプトは生成画像から除外したい要素を指定します。品質向上や特定のアーティファクト（余分な指など）の除去に効果的です。",
  },

  // ===== ドメイン2: データ準備 (26-40) =====
  {
    id: 26, domain: "データ準備",
    question: "RAGシステムのために大量のPDFドキュメントをベクトルDBに取り込む際、検索精度を維持するためにドキュメントを分割するプロセスを何と呼びますか？",
    choices: ["Partitioning", "Chunking", "Sharding", "Indexing"],
    correct: 1,
    explanation: "Chunkingはドキュメントを検索に適したサイズに分割するプロセスです。チャンクサイズとオーバーラップの設定がRAG精度に大きく影響します。",
  },
  {
    id: 27, domain: "データ準備",
    question: "チャンキングにおいて、隣接するチャンク間で一部のテキストを重複させる「オーバーラップ」を設ける主な目的は何ですか？",
    choices: ["データの冗長性を高めてバックアップにする", "チャンク境界での文脈（コンテキスト）の喪失を防ぐ", "ベクトルDBのストレージ使用量を増やす", "検索速度を速める"],
    correct: 1,
    explanation: "オーバーラップにより、チャンク境界で分断される文脈の欠落を防ぎ、検索時に適切なコンテキストが取得できるようになります。",
  },
  {
    id: 28, domain: "データ準備",
    question: "Amazon Bedrock Knowledge Basesでサポートされている、サーバーレスで自動スケーリング可能なベクトルエンジンはどれですか？",
    choices: ["Amazon Aurora (pgvector)", "Amazon OpenSearch Serverless", "Amazon RDS for MySQL", "Amazon DynamoDB"],
    correct: 1,
    explanation: "Amazon OpenSearch Serverlessのベクトルエンジンはフルマネージドでサーバーレス、Bedrock Knowledge Basesの推奨構成です。",
  },
  {
    id: 29, domain: "データ準備",
    question: "高次元の埋め込みベクトル（Embeddings）を比較して類似性を計算する際、最も一般的に使用される数学的指標はどれですか？",
    choices: ["L1 距離", "コサイン類似度 (Cosine Similarity)", "ハミング距離", "ピアソン相関係数"],
    correct: 1,
    explanation: "コサイン類似度はベクトルの向きの近さを測定し、テキストの意味的類似度計算に最も広く使われます。値が1に近いほど類似しています。",
  },
  {
    id: 30, domain: "データ準備",
    question: "Amazon Titan Text Embeddings v2 で利用可能な、ベクトルサイズを柔軟に変更しても精度を維持できる機能を何と呼びますか？",
    choices: ["Scalable Embeddings", "Matryoshka Embeddings", "Dynamic Indexing", "Sparse Vector Encoding"],
    correct: 1,
    explanation: "Matryoshka Embeddingsは入れ子構造で重要情報を前方に集約し、次元削減後も高精度を維持します。ストレージと速度のバランス調整が可能です。",
  },
  {
    id: 31, domain: "データ準備",
    question: "ベクトルデータベースにおいて、膨大なデータから近似的な最近傍を高速に検索する手法を何と呼びますか？",
    choices: ["Exact Match", "ANN (Approximate Nearest Neighbor)", "Full Table Scan", "Binary Search"],
    correct: 1,
    explanation: "ANN（近似最近傍探索）はHNSWやIVF等のアルゴリズムを使い、完全一致を犠牲にして大幅な高速化を実現します。",
  },
  {
    id: 32, domain: "データ準備",
    question: "非構造化データ（テキストファイル）からRAG用のデータセットを作成する際、メタデータ（例：作成日、著者、カテゴリ）を付与する利点は何ですか？",
    choices: ["検索結果を特定の条件でフィルタリングして精度を高めることができる", "ベクトルの次元数を減らすことができる", "暗号化が不要になる", "モデルのTemperatureを制御できる"],
    correct: 0,
    explanation: "メタデータフィルタリングにより、特定の期間・カテゴリ・著者のドキュメントのみを検索対象にでき、RAGの精度と関連性が向上します。",
  },
  {
    id: 33, domain: "データ準備",
    question: "多言語のドキュメントを扱うRAGシステムにおいて、日本語のクエリで英語の資料を検索したい場合、何が必要ですか？",
    choices: ["英語を日本語に自動翻訳するLambda", "多言語（Multilingual）対応の埋め込みモデル", "別々のベクトルDB", "モデルのファインチューニング"],
    correct: 1,
    explanation: "多言語対応の埋め込みモデルは異なる言語のテキストを同一のベクトル空間に変換するため、言語を超えた類似性検索が可能になります。",
  },
  {
    id: 34, domain: "データ準備",
    question: "埋め込みモデルが、特定の業界用語（例：自社製品の専門型番）を正しくベクトル化できない場合、精度を向上させるための「データ側」の対策はどれですか？",
    choices: ["モデルのコンテキストウィンドウを増やす", "業界用語とその説明を含む用語集をコンテキストとして追加、または埋め込みモデルの微調整を検討する", "チャンクサイズを極端に大きくする", "全てのテキストを大文字にする"],
    correct: 1,
    explanation: "専門用語集をコンテキストに追加することで、モデルが用語を正しく解釈できるようになります。埋め込みモデルの微調整も有効な対策です。",
  },
  {
    id: 35, domain: "データ準備",
    question: "Amazon OpenSearch Serverlessでベクトルエンジンを使用する際、インデックス作成に必要な設定項目はどれですか？",
    choices: ["インスタンスのインスタンスタイプ", "ベクトルの次元数（Dimensions）と類似度指標（例：nmslib/faiss）", "モデルのパラメータ数", "APIキーの有効期限"],
    correct: 1,
    explanation: "ベクトルインデックスには次元数（使用する埋め込みモデルの出力次元に合わせる）と類似度計算エンジンの指定が必須です。",
  },
  {
    id: 36, domain: "データ準備",
    question: "データの機密性が高い場合、S3に保存されたRAG用データを暗号化するための最適な方法はどれですか？",
    choices: ["パスワード付きZIPファイルにする", "AWS KMS を使用したサーバーサイド暗号化（SSE-KMS）", "データをBase64エンコードする", "データをランダムな文字で置き換える"],
    correct: 1,
    explanation: "SSE-KMSはAWS KMSのカスタムキーでS3データを暗号化し、誰がいつアクセスしたかの監査ログも取得できます。",
  },
  {
    id: 37, domain: "データ準備",
    question: "RAGにおいて「ハイブリッド検索（Hybrid Search）」とは何を指しますか？",
    choices: ["複数のLLMを同時に使うこと", "キーワードベースの検索（BM25等）とベクトルベースの検索（k-NN等）を組み合わせること", "S3とDynamoDBを同時に検索すること", "CPUとGPUを同時に使うこと"],
    correct: 1,
    explanation: "ハイブリッド検索は意味検索（ベクトル）と完全一致検索（キーワード）を組み合わせ、固有名詞や型番の検索精度も向上させます。",
  },
  {
    id: 38, domain: "データ準備",
    question: "Amazon Bedrock Knowledge Basesの「データ取り込み（Ingestion）」プロセスに含まれないステップはどれですか？",
    choices: ["文書の分割（Chunking）", "埋め込みベクトルの生成", "ベクトルストアへの保存", "モデルのフルファインチューニング"],
    correct: 3,
    explanation: "Ingestionプロセスはチャンキング→埋め込み生成→ベクトルストア保存の3ステップです。フルファインチューニングは別の最適化手法です。",
  },
  {
    id: 39, domain: "データ準備",
    question: "チャンキング戦略として「意味論的チャンキング（Semantic Chunking）」を採用する主なメリットは何ですか？",
    choices: ["計算コストが最も低い", "固定長での分割よりも、トピックの区切りを考慮したより関連性の高い情報のまとまりが作れる", "実装が最も簡単である", "全てのチャンクが同じサイズになる"],
    correct: 1,
    explanation: "Semantic Chunkingは文の意味的なまとまりを考慮して分割するため、文脈が途切れにくく、RAGの検索精度が向上します。",
  },
  {
    id: 40, domain: "データ準備",
    question: "ベクトルデータベースの「インデックス（Index）」を再構築（再同期）する必要があるのはどのような場合ですか？",
    choices: ["モデルのTemperature設定を変更したとき", "S3のソースデータが更新されたとき", "ユーザーがログインしたとき", "リージョンを切り替えたとき"],
    correct: 1,
    explanation: "S3のソースデータ（ドキュメント）が追加・更新・削除された場合、ベクトルインデックスを再同期して最新の状態に保つ必要があります。",
  },

  // ===== ドメイン3: アプリケーション開発 (41-82) =====
  {
    id: 41, domain: "アプリ開発",
    question: "Amazon Bedrock Agentsが、指示されたタスクを完了するために必要な外部ツールを呼び出すために使用する設定はどれですか？",
    choices: ["Knowledge Bases", "Action Groups", "Guardrails", "Routing"],
    correct: 1,
    explanation: "Action GroupsはOpenAPIスキーマとLambda関数を組み合わせ、エージェントが外部APIやデータベースを呼び出せるようにします。",
  },
  {
    id: 42, domain: "アプリ開発",
    question: "Amazon Bedrock AgentsとAWS Lambdaを連携させる際、Lambdaが返すレスポンスに必要な特定のフォーマットを記述する仕様書は何ですか？",
    choices: ["OpenAPI 仕様 (Swagger)", "XML スキーマ", "Dockerfile", "IAM ポリシー"],
    correct: 0,
    explanation: "Action GroupsはOpenAPI仕様（Swagger）でAPIの構造・パラメータ・レスポンスを定義し、エージェントが正しくツールを呼び出せるようにします。",
  },
  {
    id: 43, domain: "アプリ開発",
    question: "Amazon Bedrockの「InvokeModelWithResponseStream」APIを使用する際の主なメリットは何ですか？",
    choices: ["料金が安くなる", "回答全体が生成されるのを待たずに、生成されたチャンクを順次クライアントに表示できる（UXの向上）", "回答の精度が向上する", "暗号化が自動的に強化される"],
    correct: 1,
    explanation: "ストリーミングAPIはトークンが生成されるたびにリアルタイムで表示し、ユーザーの待ち時間体験を改善します。ChatGPT風のUIに必須です。",
  },
  {
    id: 44, domain: "アプリ開発",
    question: "複数のモデル（Claude、Llama、Mistral等）を単一のコード構造で呼び出すことができ、会話履歴の管理も容易にするBedrockの新しいAPIは何ですか？",
    choices: ["InvokeModel", "Converse API", "ApplyGuardrail", "ListFoundationModels"],
    correct: 1,
    explanation: "Converse APIは統一されたmessages配列形式でモデルを呼び出せ、モデル切り替えのコード変更を最小化します。プロ開発の推奨APIです。",
  },
  {
    id: 45, domain: "アプリ開発",
    question: "Amazon Bedrock Knowledge Basesを使用して、回答の「根拠（引用元）」をユーザーに提示したい場合、どのAPIメソッドを使用し、レスポンスのどのフィールドを確認すべきですか？",
    choices: ["InvokeModel の body", "RetrieveAndGenerate の citations フィールド", "GetAgent の status", "CreateKnowledgeBase の arn"],
    correct: 1,
    explanation: "RetrieveAndGenerateのcitationsフィールドには参照元ドキュメントの情報が含まれ、回答の透明性と信頼性の確保に活用できます。",
  },
  {
    id: 46, domain: "アプリ開発",
    question: "オーケストレーションツール（LangChainなど）で、モデルへの過去のメッセージ履歴を保存し、コンテキストとして再送するために使用される機能はどれですか？",
    choices: ["Chain", "Memory (ChatMessageHistory)", "Agent", "Loader"],
    correct: 1,
    explanation: "LangChainのMemoryモジュール（ChatMessageHistory等）が会話履歴を管理し、ステートレスなLLMに文脈を提供します。",
  },
  {
    id: 47, domain: "アプリ開発",
    question: "Amazon Bedrock Agentsにおいて、エージェントがユーザーの入力を受け取ってから最終的な回答を生成するまでの「内部的な推論のトレース」をデバッグするために有効な機能はどれですか？",
    choices: ["CloudWatch Metrics", "Trace capability", "AWS X-Ray (標準設定のみ)", "CloudTrail"],
    correct: 1,
    explanation: "Trace capabilityによりReActループの各ステップ（思考→アクション→観察）を可視化でき、エージェントの動作デバッグに不可欠です。",
  },
  {
    id: 48, domain: "アプリ開発",
    question: "Amazon Bedrockで「プロビジョニング済みスループット（Provisioned Throughput）」が必要となる主なシナリオはどれですか？",
    choices: ["テスト環境で時々モデルを呼び出す場合", "カスタムモデル（ファインチューニング済み）を使用する場合、またはミッションクリティカルなアプリでトラフィックを保証する場合", "S3からデータを読み込む場合", "モデルのパラメータを確認する場合"],
    correct: 1,
    explanation: "Provisioned Throughputはカスタムモデルの利用に必須であり、本番環境でのスループット保証にも使用します。",
  },
  {
    id: 49, domain: "アプリ開発",
    question: "サーバーレスフロントエンドからBedrockを呼び出す際、APIキーを直接フロントエンドに持たせないためのベストプラクティスはどれですか？",
    choices: ["APIキーを暗号化してJavaScriptに埋め込む", "Amazon API Gateway と AWS Lambda を介して、IAMロールによる一時的な認証を使用する", "APIキーをS3で公開する", "プロキシサーバーを通さず直接呼び出す"],
    correct: 1,
    explanation: "API GatewayとLambdaをバックエンドとし、IAMロールで認証することで、クライアント側にAWS認証情報を公開せずに済みます。",
  },
  {
    id: 50, domain: "アプリ開発",
    question: "BedrockのKnowledge Basesで Retrieve API（検索のみ）を使用し、その結果を自前のプロンプトに組み込んで InvokeModel を呼び出す構成を何と呼びますか？",
    choices: ["Fully Managed RAG", "Custom RAG", "Model Fine-tuning", "Prompt Compression"],
    correct: 1,
    explanation: "Custom RAGはRetrieve APIで検索を行い、取得したコンテキストを独自に整形してモデルに渡す高度なRAG構成です。プロンプト制御の自由度が高まります。",
  },
  {
    id: 51, domain: "アプリ開発",
    question: "AWS Step Functions を生成AIアプリの開発で使用する主な利点はどれですか？",
    choices: ["埋め込みベクトルを作成するため", "長時間実行される複数のステップ（例：要約 → 翻訳 → メール送信）を伴うワークフローを確実に管理するため", "モデルの推論速度を上げるため", "S3バケットを作成するため"],
    correct: 1,
    explanation: "Step Functionsは複数のLambda・Bedrock呼び出しを含む複雑なワークフローを視覚的に管理し、エラーハンドリングも容易にします。",
  },
  {
    id: 52, domain: "アプリ開発",
    question: "Amazon Bedrockにおいて、不適切なプロンプトや不適切な回答をフィルタリングするために、アプリケーションレベルで構成すべき機能は何ですか？",
    choices: ["VPCエンドポイント", "Bedrock Guardrails", "AWS Shield", "Amazon Inspector"],
    correct: 1,
    explanation: "Bedrock Guardrailsはコンテンツフィルタ・PIIマスキング・禁止トピック・ウォードフィルタなど多層的な保護を提供します。",
  },
  {
    id: 53, domain: "アプリ開発",
    question: "エージェントがアクションを実行する前に、ユーザーに最終的な承認（はい/いいえ）を求める機能を実装するにはどうすればよいですか？",
    choices: ["Lambda関数のタイムアウトを長くする", "Action Group の定義で「User Confirmation」を要求するように設定する", "モデルのTemperatureを0にする", "エージェントを削除して作り直す"],
    correct: 1,
    explanation: "User Confirmation設定により、不可逆的な操作（メール送信・注文確定など）の前にユーザーの明示的な承認を求めることができます。",
  },
  {
    id: 54, domain: "アプリ開発",
    question: "Amazon Bedrockのモデル評価（Model Evaluation）機能で、人間が回答の「ブランドの声」や「創造性」を評価する際に使用できるワークフォースはどれですか？",
    choices: ["Amazon Mechanical Turk", "AWS Managed Workforce (または自社/ベンダーのワークフォース)", "AWS Lambda", "Amazon EC2"],
    correct: 1,
    explanation: "Bedrock Model EvaluationのHuman評価では、AWSマネージドワークフォースまたは自社の評価者チームを指定して主観的な品質評価ができます。",
  },
  {
    id: 55, domain: "アプリ開発",
    question: "BedrockのKnowledge Basesで、特定のドキュメントのみを検索対象にしたい場合、どのように実装しますか？",
    choices: ["全ドキュメントを1つのファイルにする", "RetrievalConfiguration でメタデータフィルタリングを適用する", "ベクトルDBを毎回作り直す", "モデルのプロンプトで「そのユーザー以外は見ないで」と頼む"],
    correct: 1,
    explanation: "メタデータフィルタリングを使うと、ユーザーIDやカテゴリ等のメタデータに基づいて検索対象ドキュメントを絞り込めます。",
  },
  {
    id: 56, domain: "アプリ開発",
    question: "Bedrock APIの呼び出しで「ThrottlingException（429）」が発生しました。最も適切なクライアント側の対応はどれですか？",
    choices: ["即座に無限ループで再試行する", "指数バックオフ（Exponential Backoff）とジッター（Jitter）を伴うリトライロジックを実装する", "リージョンを変更して再度試す", "AWSサポートに電話する"],
    correct: 1,
    explanation: "指数バックオフはリトライ間隔を指数的に延ばし、ジッターはランダム性を加えることでサービスへの負荷集中を防ぎます。",
  },
  {
    id: 57, domain: "アプリ開発",
    question: "Amazon Bedrockで大規模なバッチ推論ジョブ（数百万件のデータ）を非同期で実行したい場合に最適なAPIはどれですか？",
    choices: ["InvokeModel", "CreateModelInvocationJob", "RetrieveAndGenerate", "InvokeAgent"],
    correct: 1,
    explanation: "CreateModelInvocationJob（Batch Inference）は非同期で大量データを処理し、リアルタイムクォータを消費せず、コストも最大50%削減できます。",
  },
  {
    id: 58, domain: "アプリ開発",
    question: "ストリーミングレスポンスにおいて、各チャンクがどのような形式で配信されるかを知るために参照すべき技術概念は何ですか？",
    choices: ["REST", "EventStream (Server-Sent Events 形式)", "GraphQL", "SOAP"],
    correct: 1,
    explanation: "BedrockのストリーミングはEventStream形式でチャンクを配信します。クライアント側でイベントを受け取りリアルタイム表示します。",
  },
  {
    id: 59, domain: "アプリ開発",
    question: "Bedrockのエージェントをデプロイする際、開発用と本番用でバージョンを分けるために使用される仕組みは何ですか？",
    choices: ["IAM グループ", "エージェントのエイリアス（Aliases）とバージョン（Versions）", "S3 バケット名", "リージョン名"],
    correct: 1,
    explanation: "エージェントのバージョン管理にはAliasとVersionを使用します。エイリアスで本番/開発を切り替え、ロールバックも容易です。",
  },
  {
    id: 60, domain: "アプリ開発",
    question: "LangChainの「Chain」が果たす主な役割は何ですか？",
    choices: ["ベクトルを保存すること", "LLM、プロンプト、データ処理などの一連のコンポーネントを連結し、一つのタスクとして実行すること", "ネットワークの帯域を広げること", "モデルをトレーニングすること"],
    correct: 1,
    explanation: "LangChainのChainはプロンプトテンプレート・LLM呼び出し・出力パーサーなどを直列に連結して複雑な処理フローを構築します。",
  },
  {
    id: 61, domain: "アプリ開発",
    question: "BedrockのConverse APIにおいて、会話の文脈を維持するためにリクエストに含めるべき主要なパラメータは何ですか？",
    choices: ["systemPrompt", "messages (過去の対話履歴を含む配列)", "stopSequences", "guardrailConfig"],
    correct: 1,
    explanation: "Converse APIのmessages配列に過去のuser/assistantのやり取りを含めることで、LLMに会話の文脈を提供します。",
  },
  {
    id: 62, domain: "アプリ開発",
    question: "RAGシステムにおいて、検索されたコンテキストが長すぎてモデルの入力制限を超える場合、どのような対策が有効ですか？",
    choices: ["モデルを削除する", "プロンプト圧縮（Prompt Compression）を使用するか、検索結果のランク付け（Reranking）を行い、上位のみを採用する", "コンテキストをすべて無視する", "全てのテキストを画像にする"],
    correct: 1,
    explanation: "Rerankingで最も関連性の高いチャンクを選別するか、プロンプト圧縮で情報を凝縮することでコンテキスト長を管理します。",
  },
  {
    id: 63, domain: "アプリ開発",
    question: "Amazon Bedrock Agentsで、指示（Instructions）に記述すべき内容として適切でないものはどれですか？",
    choices: ["エージェントの役割（例：親切な旅行ガイド）", "エージェントが実行すべきタスクのステップ", "データベースのルートパスワード", "エージェントが守るべきトーンや制約"],
    correct: 2,
    explanation: "機密情報（パスワード・APIキー等）はAgentのInstructionsに記述すべきではありません。Secrets Managerなど適切なサービスを使用します。",
  },
  {
    id: 64, domain: "アプリ開発",
    question: "モデルが特定のツール（Action Group）を呼び出すべきかどうかを判断するために、内部で行っているのはどのようなプロセスですか？",
    choices: ["ユーザーの入力をランダムに処理する", "モデルが入力からインテント（意図）とパラメータを抽出し、事前定義されたツール記述と比較する", "全てのツールを順番に実行する", "何もしない"],
    correct: 1,
    explanation: "モデルはOpenAPI仕様で定義されたツールの説明文とユーザーの意図を照合し、適切なツールとパラメータを選択します。",
  },
  {
    id: 65, domain: "アプリ開発",
    question: "Bedrockの RetrieveAndGenerate APIで、回答の引用元ドキュメントのS3パスを表示したい場合、フロントエンドで何を処理する必要がありますか？",
    choices: ["レスポンスの text だけを表示する", "レスポンスの citations 内の retrievedReferences から location 情報を取得し表示する", "ユーザーにS3を検索させる", "S3バケットをパブリックにする"],
    correct: 1,
    explanation: "citationsフィールド内のretrievedReferences.locationにS3パスが含まれます。これをUIで表示することで回答の根拠を示せます。",
  },
  {
    id: 66, domain: "アプリ開発",
    question: "Amazon Bedrockにおいて、モデルが「自分が何を知らないか」を認め、不確かな回答を避けるようにするためのプロンプトの工夫はどれですか？",
    choices: ["「自信がなくても何でも答えてください」と書く", "「提供された情報に答えが含まれていない場合は、正直に分かりませんと答えてください」と指示する", "Temperatureを1.0にする", "回答の長さを最小限にする"],
    correct: 1,
    explanation: "不確実性を認めるよう明示的に指示することで、ハルシネーションを抑制し、信頼性の高いRAGシステムを構築できます。",
  },
  {
    id: 67, domain: "アプリ開発",
    question: "AWS LambdaをBedrock Agentsのアクションとして使用する際、Lambda関数のタイムアウト設定に関する注意点は何ですか？",
    choices: ["常に1秒にする必要がある", "モデルの推論時間やAPI呼び出しにかかる時間を考慮し、エージェントのデフォルト制限内で適切に設定する必要がある", "タイムアウトは無視される", "タイムアウトを1時間にする必要がある"],
    correct: 1,
    explanation: "Lambdaのタイムアウトはエージェントの処理時間（推論+外部API呼び出し）を考慮して設定します。デフォルトの3秒では不十分なことが多いです。",
  },
  {
    id: 68, domain: "アプリ開発",
    question: "生成AIアプリにおいて、ユーザーのセッション情報をDynamoDBに保存する主な理由は何ですか？",
    choices: ["画像を保存するため", "ステートレスなLambda関数の実行間で、会話履歴（セッション状態）を永続化し維持するため", "モデルの重みを保存するため", "ネットワークを高速化するため"],
    correct: 1,
    explanation: "LambdaはステートレスなのでDynamoDBに会話履歴を保存し、次のリクエスト時に読み込んでコンテキストとして使用します。",
  },
  {
    id: 69, domain: "アプリ開発",
    question: "Bedrock Guardrailsにおいて「PiiEntitiesConfig」は何を設定するために使用しますか？",
    choices: ["サーバーのIPアドレス", "住所、氏名、電話番号などの個人を特定できる情報（PII）の検知としきい値", "モデルのパラメータ", "ベクトルDBのサイズ"],
    correct: 1,
    explanation: "PiiEntitiesConfigでPIIの種類（氏名・住所・クレジットカード番号など）とアクション（マスク・ブロック等）を設定します。",
  },
  {
    id: 70, domain: "アプリ開発",
    question: "「ReAct」フレームワークにおいて、モデルが行う「Observation（観察）」とは何を指しますか？",
    choices: ["モデルが自分の考えを述べること", "外部ツールや検索から返ってきた結果を確認すること", "ユーザーが画面を見ること", "モデルがシャットダウンすること"],
    correct: 1,
    explanation: "ReActのObservationはツール実行結果（API応答・検索結果等）を受け取って確認するステップです。次のThoughtの入力となります。",
  },
  {
    id: 71, domain: "アプリ開発",
    question: "Amazon Bedrockのモデル呼び出しにおける「トークン数」のカウント方法に最も影響を与えるのはどれですか？",
    choices: ["使用している文字コード（UTF-8）のバイト数", "モデル固有のトークナイザーによる単語や部分単語の分割", "ネットワークのパケット数", "CPUのクロック数"],
    correct: 1,
    explanation: "トークン数はモデル固有のトークナイザーによって決まります。同じテキストでもモデルによって異なるトークン数になります。",
  },
  {
    id: 72, domain: "アプリ開発",
    question: "BedrockのConverse APIで「Tool use（ツール使用）」機能を実装する際、ツール（関数）の定義に含めるべき情報はどれですか？",
    choices: ["サーバーのログイン情報", "ツールの名前、説明、および入力引数のJSONスキーマ", "ツールのソースコード全体", "全ての過去の実行ログ"],
    correct: 1,
    explanation: "ツール定義には名前・説明（モデルが判断に使う）・入力パラメータのJSONスキーマが必要です。説明が明確なほどモデルの判断精度が向上します。",
  },
  {
    id: 73, domain: "アプリ開発",
    question: "RAGアプリケーションにおいて、ユーザーの質問を一度モデルに渡し、より検索に適したクエリに変換させる手法を何と呼びますか？",
    choices: ["Query Rewriting (クエリの書き換え)", "Vector Normalization", "Model Quantization", "Token Pruning"],
    correct: 0,
    explanation: "Query Rewritingはユーザーの口語的・曖昧な質問を検索に最適化されたクエリに変換し、RAGの検索精度を向上させます。",
  },
  {
    id: 74, domain: "アプリ開発",
    question: "Amazon Bedrockで「カスタムモデル（Custom Model）」を作成した後、そのモデルを削除せずに維持する際のコストに関連するコンポーネントはどれですか？",
    choices: ["モデルのダウンロード料金", "モデルのストレージ料金（カスタムモデル自体の保存コスト）", "CPU使用料", "入力トークン料のみ"],
    correct: 1,
    explanation: "カスタムモデルは作成後、使用しない期間もストレージ料金が発生します。不要なカスタムモデルは削除してコストを管理することが重要です。",
  },
  {
    id: 75, domain: "アプリ開発",
    question: "モデルの出力を構造化データ（例：CSV）として取得したい場合に、プロンプトに含めるべき最良の指示はどれですか？",
    choices: ["「表形式にして」", "「以下のヘッダー（列名）を持つCSV形式で出力し、他の説明文は一切含めないでください」と具体的に指示し、例を示す", "「なるべく短くして」", "何も書かない"],
    correct: 1,
    explanation: "具体的なフォーマット指定と例示が最も効果的です。「説明文を含めない」と明示することで後処理が不要なクリーンな出力が得られます。",
  },
  {
    id: 76, domain: "アプリ開発",
    question: "Amazon Bedrockで複数のリージョン（例：東京とバージニア）を利用するマルチリージョン構成にする主なメリットは何ですか？",
    choices: ["料金が常に半分になる", "1つのリージョンで障害やクォータ制限が発生した場合の可用性とレジリエンスの向上", "モデルのパラメータが増える", "管理が簡単になる"],
    correct: 1,
    explanation: "マルチリージョン構成はフェイルオーバーとクォータ制限回避のために使用します。Cross-Region Inferenceを使うと自動ルーティングも可能です。",
  },
  {
    id: 77, domain: "アプリ開発",
    question: "BedrockのKnowledge Basesで「Hybrid Search」を有効にした場合、どのように動作しますか？",
    choices: ["2つのLLMが同時に答える", "ベクトル検索とキーワード検索（テキストマッチング）を並行して行い、結果を統合（Rerank）して最適なコンテキストを抽出する", "データベースが2つ必要になる", "暗号化が2回行われる"],
    correct: 1,
    explanation: "Hybrid SearchはベクトルとBM25の両方で検索し、RRF等でスコアを統合します。固有名詞と意味検索の両方に強い構成です。",
  },
  {
    id: 78, domain: "アプリ開発",
    question: "開発者がBedrockのAPIを使用して画像からテキストを抽出（OCR）したい場合、どのモデルファミリーが一般的に適していますか？",
    choices: ["Titan Text", "Claude 3 (Vision機能を備えたモデル)", "Llama 2", "Cohere Command"],
    correct: 1,
    explanation: "Claude 3はVision機能を持つマルチモーダルモデルで、画像の解析・テキスト抽出・説明生成などが可能です。",
  },
  {
    id: 79, domain: "アプリ開発",
    question: "Bedrockの RetrieveAndGenerate APIを使用する際、デフォルトのシステムプロンプトを上書きして、回答のトーンを変更することは可能ですか？",
    choices: ["いいえ、変更できません", "はい、GenerationConfiguration 内のプロンプトテンプレートを指定することで可能です", "はい、ベクトルDBの設定を変更すれば可能です", "いいえ、モデル自体を再学習する必要があります"],
    correct: 1,
    explanation: "GenerationConfigurationのpromptTemplateでシステムプロンプトをカスタマイズでき、ブランドのトーンや言語スタイルを指定できます。",
  },
  {
    id: 80, domain: "アプリ開発",
    question: "エージェントがアクションを実行する際に必要なパラメータが不足している場合、Bedrock Agentsはどう動作しますか？",
    choices: ["エラーを出して終了する", "ユーザーに不足している情報を尋ねる（指示に基づき対話を継続する）", "適当な値を捏造する", "無限ループに入る"],
    correct: 1,
    explanation: "Bedrock Agentsはパラメータが不足している場合、エラーを出す前にユーザーに必要な情報を質問して対話的に収集します。",
  },
  {
    id: 81, domain: "アプリ開発",
    question: "Bedrockの「Batch Inference（バッチ推論）」ジョブの入力データとして使用されるファイル形式は何ですか？",
    choices: [".exe", "JSONL (JSON Lines)", ".mp3", ".png"],
    correct: 1,
    explanation: "Batch InferenceはJSONL形式（1行1リクエスト）をS3に配置して実行します。大量データの非同期処理に最適です。",
  },
  {
    id: 82, domain: "アプリ開発",
    question: "Amazon Bedrockで提供される「マーケットプレイスモデル」を使用するために、まず何を行う必要がありますか？",
    choices: ["独自のサーバーを立てる", "Bedrockのコンソール（Model access）で使用したいモデルのアクセス権をリクエストし、有効化する", "モデルをダウンロードする", "AWSに個別に電話で申請する"],
    correct: 1,
    explanation: "Bedrockのモデルはデフォルトで無効です。コンソールのModel accessページでモデルごとにアクセスを有効化する必要があります。",
  },

  // ===== ドメイン4: 評価と最適化 (83-123) =====
  {
    id: 83, domain: "評価と最適化",
    question: "要約タスクにおいて、モデルが生成した要約が正解（リファレンス）の要約とどの程度語彙が重なっているかを測定する、最も一般的な指標はどれですか？",
    choices: ["BLEU", "ROUGE", "Perplexity", "F1"],
    correct: 1,
    explanation: "ROUGEは要約評価の標準指標で、特にROUGE-Nは単語の重複、ROUGE-Lは最長共通部分列を測定します。再現率重視の指標です。",
  },
  {
    id: 84, domain: "評価と最適化",
    question: "Amazon Bedrockで「ファインチューニング（Fine-tuning）」を実行する際、基盤モデルの全ての重みを変更するのではなく、特定の小さな行列を追加して学習させる効率的な手法を何と呼びますか？",
    choices: ["Full fine-tuning", "LoRA (Low-Rank Adaptation)", "Continuous Pre-training", "Direct Preference Optimization (DPO)"],
    correct: 1,
    explanation: "LoRAは低ランク行列を元のパラメータに追加し、少ないメモリと時間でファインチューニングできます。Bedrockでサポートされています。",
  },
  {
    id: 85, domain: "評価と最適化",
    question: "RAGシステムにおいて、検索されたドキュメントがユーザーの質問に答えるためにどれだけ適切（関連性がある）かを評価する指標をRAGASでは何と呼びますか？",
    choices: ["Faithfulness", "Answer Relevance", "Context Precision", "Context Recall"],
    correct: 1,
    explanation: "Answer Relevanceは生成された回答がユーザーの質問にどれだけ直接的に答えているかを評価します。RAGASの主要指標の一つです。",
  },
  {
    id: 86, domain: "評価と最適化",
    question: "モデルが生成した回答の中に、検索されたコンテキストに基づかない情報（ハルシネーション）が含まれていないかを評価する指標を何と呼びますか？",
    choices: ["Faithfulness (忠実性)", "Answer Relevance", "Latency", "BLEU"],
    correct: 0,
    explanation: "Faithfulnessは回答が検索されたソース（根拠）に基づいているかを評価し、ハルシネーションを検出するRAGASの核心的な指標です。",
  },
  {
    id: 87, domain: "評価と最適化",
    question: "Amazon Bedrockの「モデル評価（Model Evaluation）」で「自動（Automatic）」を選択した場合、どのような評価が実行されますか？",
    choices: ["実際のユーザーが評価する", "設定したデータセットに基づき、アルゴリズムが正確性、毒性、堅牢性などの指標を計算する", "AIが自ら学習をやり直す", "回答がSNSに投稿される"],
    correct: 1,
    explanation: "自動評価では定義済みのデータセットを使ってROUGE・BERTScore・毒性スコアなどを自動計算します。人手なしで大規模評価が可能です。",
  },
  {
    id: 88, domain: "評価と最適化",
    question: "推論コストを最適化するために、モデルの精度を保ちつつメモリ使用量を減らすための技術で、重みのデータ型を（FP32からINT8など）変換することを何と呼びますか？",
    choices: ["Distillation", "Quantization (量子化)", "Pruning (枝刈り)", "Sharding"],
    correct: 1,
    explanation: "量子化はパラメータの数値精度を下げてモデルを軽量化します。FP16やINT8への変換でメモリと推論速度が改善されます。",
  },
  {
    id: 89, domain: "評価と最適化",
    question: "特定のタスクに特化させるために、大きな教師モデル（Teacher）の出力を、より小さな生徒モデル（Student）に学習させる手法を何と呼びますか？",
    choices: ["Fine-tuning", "Knowledge Distillation (蒸留)", "RLHF", "Batch Inference"],
    correct: 1,
    explanation: "Knowledge Distillationは大モデルの「軟らかい出力（確率分布）」を使って小モデルを訓練し、小さなモデルで高性能を実現します。",
  },
  {
    id: 90, domain: "評価と最適化",
    question: "Amazon Bedrockで「プロビジョニング済みスループット（Provisioned Throughput）」を時間単位で購入する際、最小の購入単位は何ですか？",
    choices: ["1秒", "1分", "1時間（ただし購入単位は通常モデルユニット数に依存）", "1ヶ月"],
    correct: 2,
    explanation: "Provisioned Throughputは最小1時間単位で購入します。長期（1ヶ月・6ヶ月）の割引オプションも提供されています。",
  },
  {
    id: 91, domain: "評価と最適化",
    question: "モデルが次にくる単語を予測する際の「迷い」の度合いを示し、言語モデルの性能を評価する代表的な指標は何ですか？",
    choices: ["Perplexity (パープレキシティ)", "Accuracy", "Recall", "Precision"],
    correct: 0,
    explanation: "Perplexityはモデルがテストデータをどれだけ驚き少なく予測できるかを示します。低いほど良い言語モデルであることを示します。",
  },
  {
    id: 92, domain: "評価と最適化",
    question: "RAGの検索精度を向上させるために、ベクトル検索で得られた上位N件の結果を、より高性能なモデルやアルゴリズムで再度ランク付けし直す手法を何と呼びますか？",
    choices: ["Pre-ranking", "Reranking", "Chunking", "Normalization"],
    correct: 1,
    explanation: "Rerankingは初期検索（高速・大量）の後に精密な関連性スコアリングを行い、最終的なコンテキストの質を向上させます。",
  },
  {
    id: 93, domain: "評価と最適化",
    question: "Amazon SageMaker Clarifyを使用する主な目的は何ですか？",
    choices: ["モデルの学習を加速すること", "モデルのバイアス（偏り）を検出し、予測結果の説明可能性を提供すること", "データベースをバックアップすること", "VPCの設定をチェックすること"],
    correct: 1,
    explanation: "SageMaker ClarifyはSHAP値を使ってモデルの予測根拠を説明し、データ・モデルのバイアスを検出します。責任あるAIの実践に重要です。",
  },
  {
    id: 94, domain: "評価と最適化",
    question: "LoRAを使用してファインチューニングを行う際の「ランク（Rank）」パラメータについて、正しい説明はどれですか？",
    choices: ["ランクが高いほど学習可能なパラメータが増え、表現力が上がるが、メモリと時間がかかる", "ランクは常に1であるべきである", "ランクが高いほど推論が速くなる", "ランクはモデルの層数を表す"],
    correct: 0,
    explanation: "LoRAのRankは学習する低ランク行列のサイズを決定します。高いRankは表現力増大の一方でメモリと計算コストが増加します。",
  },
  {
    id: 95, domain: "評価と最適化",
    question: "Amazon Bedrockにおいて、ファインチューニングがサポートされているモデルはどれですか？（2024年時点の一般的知識）",
    choices: ["すべてのマーケットプレイスモデル", "Amazon Titan、一部のClaude、Llama、Cohereなどの対応モデル", "自作のモデルのみ", "モデルは一切変更できない"],
    correct: 1,
    explanation: "Bedrockのファインチューニングは全モデルで使えるわけではありません。Amazon Titan・一部のClaude・Llama・Cohereなどが対応しています。",
  },
  {
    id: 96, domain: "評価と最適化",
    question: "モデル評価における「堅牢性（Robustness）」とは何を測定するものですか？",
    choices: ["モデルの回答速度", "プロンプトのわずかな変化（例：誤字、言い回しの変更）に対して、回答がどれだけ一貫性を保てるか", "サーバーの耐久性", "ネットワークの安定性"],
    correct: 1,
    explanation: "堅牢性は入力の微妙な変化に対してモデルが一貫した高品質な回答を維持できるかを評価します。実運用での信頼性に直結します。",
  },
  {
    id: 97, domain: "評価と最適化",
    question: "生成AIのモデル評価において「Ground Truth（グラウンド・トゥルース）」とは何を指しますか？",
    choices: ["モデルの重みの値", "人間が作成した「正解データ」", "データベースの名前", "インターネット上の全データ"],
    correct: 1,
    explanation: "Ground Truthは人間の専門家が作成した正解データで、自動評価指標（ROUGE・BLEU等）の比較基準として使用します。",
  },
  {
    id: 98, domain: "評価と最適化",
    question: "RLHF（Reinforcement Learning from Human Feedback）において、人間が行う主な作業は何ですか？",
    choices: ["モデルのコードを書くこと", "複数のモデルの回答を比較し、より良いものにランクを付けること", "サーバーを物理的に管理すること", "プロンプトを削除すること"],
    correct: 1,
    explanation: "RLHFでは人間がモデルの複数の回答を比較評価し、そのフィードバックを使って報酬モデルを学習し、PPOなどで最適化します。",
  },
  {
    id: 99, domain: "評価と最適化",
    question: "Amazon Bedrockの「Batch Inference」を使用する際、コスト削減以外に期待できるメリットは何ですか？",
    choices: ["リアルタイム性が向上する", "数百万のリクエストを同時実行しても、リアルタイム推論のクォータを消費せずに大量処理できる", "モデルの精度が劇的に上がる", "ネットワーク遅延がゼロになる"],
    correct: 1,
    explanation: "Batch Inferenceはリアルタイムクォータを消費せず大量処理でき、データ分析・バルク評価・非同期処理に最適です。",
  },
  {
    id: 100, domain: "評価と最適化",
    question: "RAGシステムの評価で、検索された情報がどれだけ「過不足なく」質問に答えるために必要十分であるかを評価する指標は何ですか？",
    choices: ["Context Precision (適合率) と Context Recall (再現率)", "ROUGE-L", "Token count", "Cost per query"],
    correct: 0,
    explanation: "Context Precisionは検索結果の中で関連するものの割合（精度）、Context Recallは必要な情報が検索できているかの割合（再現率）を測定します。",
  },
  {
    id: 101, domain: "評価と最適化",
    question: "モデルの量子化において「FP16」から「INT8」に変換すると、メモリ消費量は理論上どうなりますか？",
    choices: ["変わらない", "約半分になる", "2倍になる", "0になる"],
    correct: 1,
    explanation: "FP16は16ビット、INT8は8ビットなので、理論上メモリ消費量は約半分になります。推論速度も向上します。",
  },
  {
    id: 102, domain: "評価と最適化",
    question: "AWS Trainium や AWS Inferentia を使用する主な目的は何ですか？",
    choices: ["プログラミングを自動化するため", "深層学習のトレーニング（Trainium）や推論（Inferentia）において、高いコストパフォーマンスとパフォーマンスを実現するため", "ストレージ容量を増やすため", "画像を編集するため"],
    correct: 1,
    explanation: "TrainiumはMLトレーニング向け、InferentiaはML推論向けのAWSカスタムチップです。GPUより高いコストパフォーマンスを実現します。",
  },
  {
    id: 103, domain: "評価と最適化",
    question: "「DPO (Direct Preference Optimization)」がRLHFの代替として注目されている主な理由は何ですか？",
    choices: ["より大規模なサーバーが必要だから", "報酬モデル（Reward Model）の学習を必要とせず、直接人間の好みを学習できるため実装がシンプルになる", "精度が低いから", "無料だから"],
    correct: 1,
    explanation: "DPOはRLHFの複雑な報酬モデル学習+RL最適化を、シンプルな分類問題として定式化することで実装を大幅に簡略化します。",
  },
  {
    id: 104, domain: "評価と最適化",
    question: "モデルが「特定の文体（例：シェイクスピア風）」を学習するのに最も適した手法はどれですか？",
    choices: ["ネットワークを高速化する", "スタイルを反映したデータセットを用いたファインチューニング", "モデルを削除する", "リージョンを変更する"],
    correct: 1,
    explanation: "特定の文体・スタイルを習得させるにはその文体のデータでファインチューニングするのが最も効果的です。",
  },
  {
    id: 105, domain: "評価と最適化",
    question: "Amazon Bedrockで「Provisioned Throughput」を削除（解除）すると、関連付けられたカスタムモデルはどうなりますか？",
    choices: ["モデル自体が削除される", "モデルは保存されたままだが、再度スループットを割り当てるまで推論に使用できなくなる", "モデルが一般公開される", "モデルがベースモデルに戻る"],
    correct: 1,
    explanation: "Provisioned Throughputを解除してもカスタムモデル自体は保存されます。再利用するには再度スループットを割り当てる必要があります。",
  },
  {
    id: 106, domain: "評価と最適化",
    question: "モデル評価における「毒性（Toxicity）」の定義は何ですか？",
    choices: ["モデルが動作しなくなるバグ", "ヘイトスピーチ、差別、暴力的な表現など、有害な内容を含む度合い", "電力の消費量", "ファイルのウイルス感染"],
    correct: 1,
    explanation: "毒性スコアはモデルが生成するヘイトスピーチ・差別・暴力的表現の割合を測定します。コンテンツポリシー遵守の評価に使用します。",
  },
  {
    id: 107, domain: "評価と最適化",
    question: "「Few-shotプロンプティング」で、例示の数を増やす（例：1件から10件）と、一般的にモデルの挙動はどう変化しますか？",
    choices: ["常に精度が下がる", "特定のタスク形式に従いやすくなるが、プロンプトのトークン消費量と計算コストが増える", "推論速度が速くなる", "何も変わらない"],
    correct: 1,
    explanation: "例示数を増やすとモデルがパターンをより強く学習しますが、トークン消費が増え、コストと入力制限に注意が必要です。",
  },
  {
    id: 108, domain: "評価と最適化",
    question: "RAGにおいて、埋め込みモデル自体をファインチューニングする（Embedding Fine-tuning）ことが有効なのはどのような場合ですか？",
    choices: ["一般的な用語しか使わない場合", "業界固有の専門用語や、特殊な意味を持つ略語が頻出する独自のドメイン知識を扱う場合", "ネットワークが遅い場合", "モデルのアイコンを変えたい場合"],
    correct: 1,
    explanation: "専門用語・業界固有の略語は汎用埋め込みモデルで適切にベクトル化されないことがあります。ドメイン固有のデータでの微調整が有効です。",
  },
  {
    id: 109, domain: "評価と最適化",
    question: "ユーザーが「回答が長すぎる」と苦情を言っています。コストとユーザー体験を最適化するための最も簡単な対策はどれですか？",
    choices: ["モデルをより大きくする", "プロンプトで回答の最大語数を指定するか、モデルパラメータの maxTokens を制限する", "ユーザーをブロックする", "サーバーを増設する"],
    correct: 1,
    explanation: "maxTokensパラメータで出力長を制限し、プロンプトでも「〇〇語以内で」と指示することで、コストとUXの両方を改善できます。",
  },
  {
    id: 110, domain: "評価と最適化",
    question: "LLM-as-a-judge（LLMを評価者として使う）手法のメリットは何ですか？",
    choices: ["人間による評価よりも常に正確である", "大規模な評価を高速かつ低コストに実施でき、人間と相関の高い評価が得られる可能性がある", "評価が不要になる", "コンピュータの電源を切れる"],
    correct: 1,
    explanation: "LLM-as-a-judgeは人間評価者の代替として大量の回答を自動評価でき、スケーラブルな品質管理に活用されます。",
  },
  {
    id: 111, domain: "評価と最適化",
    question: "モデルの「パラメータ効率の高い微調整（PEFT）」とは何を目的としていますか？",
    choices: ["全パラメータを学習させること", "モデルのごく一部のパラメータのみを更新し、元のモデルの知識を維持しつつ低リソースで特定のタスクに適応させること", "モデルを大きくすること", "パラメータをランダムに変えること"],
    correct: 1,
    explanation: "PEFTはLoRA・Adapter・Prefix Tuningなどの手法で少量のパラメータのみ更新し、フルファインチューニングより低コスト・高効率です。",
  },
  {
    id: 112, domain: "評価と最適化",
    question: "Amazon Bedrockでファインチューニングジョブが失敗した場合、まず確認すべきことは何ですか？",
    choices: ["S3のトレーニングデータのパス、フォーマット、およびIAMロールの権限", "インターネットの速度", "マウスの電池", "SNSの通知設定"],
    correct: 0,
    explanation: "ファインチューニング失敗の主な原因はS3パスの誤り・データフォーマットエラー・IAM権限不足です。CloudWatch Logsで詳細を確認します。",
  },
  {
    id: 113, domain: "評価と最適化",
    question: "「セマンティック検索」の弱点は何ですか？",
    choices: ["意味が似ているものを探せないこと", "特定の製品番号や固有名詞などの「完全一致」が必要な検索において、キーワード検索より精度が落ちる場合があること", "速度が速すぎること", "誰でも使えること"],
    correct: 1,
    explanation: "セマンティック検索は意味的類似性が得意ですが、「ABC-123」のような固有のコードや型番の完全一致検索はキーワード検索が優れています。",
  },
  {
    id: 114, domain: "評価と最適化",
    question: "評価指標「METEOR」がBLEUよりも優れているとされる点はどこですか？",
    choices: ["計算が速い", "語形変化（動詞の活用など）や類義語を考慮して評価できる点", "名前がかっこいい", "全てのモデルで使える"],
    correct: 1,
    explanation: "METEORはステミング・同義語・語順を考慮した柔軟な評価が可能で、BLEUより人間の評価との相関が高いとされています。",
  },
  {
    id: 115, domain: "評価と最適化",
    question: "RAGにおいて「Reciprocal Rank Fusion (RRF)」は何に使用されますか？",
    choices: ["画像の圧縮", "キーワード検索とベクトル検索という異なる手法の検索結果を統合し、最終的なランキングを決定するため", "パスワードの暗号化", "S3の並列読み込み"],
    correct: 1,
    explanation: "RRFは複数の検索手法のランキングを組み合わせるアルゴリズムで、ハイブリッド検索の結果統合に広く使用されます。",
  },
  {
    id: 116, domain: "評価と最適化",
    question: "モデルが「同じフレーズを何度も繰り返す」現象（繰り返し問題）を改善するために調整すべきパラメータは何ですか？",
    choices: ["Temperatureを0にする", "Presence penalty (存在ペナルティ) や Frequency penalty (頻度ペナルティ) を上げる", "ストリーミングをオフにする", "入力トークンを減らす"],
    correct: 1,
    explanation: "Presence penaltyは既出のトークンにペナルティを与え、Frequency penaltyは出現頻度に応じてペナルティを増やします。繰り返しの抑制に効果的です。",
  },
  {
    id: 117, domain: "評価と最適化",
    question: "Amazon Bedrockでの「継続的な事前学習（Continuous Pre-training）」の用途は何ですか？",
    choices: ["1つずつのプロンプトに答える", "モデルに特定のドメイン（例：医学、法律）の膨大な「ラベルなしテキスト」を学習させ、ドメイン知識を深めること", "モデルを削除する", "ロゴを作成する"],
    correct: 1,
    explanation: "Continuous Pre-trainingはラベルなしの大量ドメインテキストでモデルの基礎知識を拡張します。Fine-tuningと組み合わせて使用されます。",
  },
  {
    id: 118, domain: "評価と最適化",
    question: "推論時のコストを計算する際、最も影響を与える要素は何ですか？",
    choices: ["入力トークン数と出力トークン数（および使用モデルの単価）", "画面の明るさ", "ユーザーの所在地", "ブラウザの種類"],
    correct: 0,
    explanation: "Bedrockの推論コストは入力トークン数×入力単価＋出力トークン数×出力単価で計算されます。出力トークンの方が高いことが多いです。",
  },
  {
    id: 119, domain: "評価と最適化",
    question: "「Few-shot」の例示を選ぶ際、どのような例を選ぶのが最も効果的ですか？",
    choices: ["全く関係ないジャンルの例", "多様性があり、且つユーザーが実際に行うタスクに近い形式と難易度の例", "最も簡単な例だけ", "最も長い例だけ"],
    correct: 1,
    explanation: "実際のユースケースに近い多様な例示を選ぶことで、モデルが期待するタスク形式を正確に学習し、精度が向上します。",
  },
  {
    id: 120, domain: "評価と最適化",
    question: "Amazon Bedrockのモデル評価の結果を可視化するために統合できるサービスはどれですか？",
    choices: ["Amazon QuickSight (S3経由のレポート分析など)", "AWS Glue", "AWS IoT Core", "Amazon WorkMail"],
    correct: 0,
    explanation: "モデル評価の結果はS3に出力され、Amazon QuickSightやAthenaで可視化・分析できます。",
  },
  {
    id: 121, domain: "評価と最適化",
    question: "モデルの量子化によって引き起こされる可能性がある主なデメリットは何ですか？",
    choices: ["推論が遅くなる", "僅かな推論精度の低下（パープレキシティの上昇）", "コストが上がる", "サーバーが物理的に壊れる"],
    correct: 1,
    explanation: "量子化はメモリと速度を改善しますが、数値精度の低下により推論品質が若干落ちることがあります。精度と効率のトレードオフです。",
  },
  {
    id: 122, domain: "評価と最適化",
    question: "RAGの「リトリーバル（検索）」フェーズを最適化するために、ユーザーのクエリを拡張して複数の類似クエリを生成する手法を何と呼びますか？",
    choices: ["Query Expansion (クエリ拡張)", "Index Pruning", "Token Masking", "Model Sharding"],
    correct: 0,
    explanation: "Query Expansionはユーザーの一つの質問から複数のバリエーションを生成し、検索の網羅性を高めてRAGの再現率を向上させます。",
  },
  {
    id: 123, domain: "評価と最適化",
    question: "生成AIのガバナンスにおいて「説明可能性（Explainability）」が必要とされる主な理由はどれですか？",
    choices: ["ユーザーを楽しませるため", "なぜモデルがその回答を出したのか、特に倫理的・法的判断が関わる場合に、その根拠やプロセスを透明にするため", "プログラミングを難しくするため", "AWSの料金を下げるため"],
    correct: 1,
    explanation: "説明可能性は医療・金融・法律など高リスク分野でのAI採用に不可欠で、規制対応と信頼確保のために必要です。",
  },

  // ===== ドメイン5: セキュリティとガバナンス (124-150) =====
  {
    id: 124, domain: "セキュリティ",
    question: "Amazon Bedrockを利用する際、顧客データがモデルプロバイダー（Anthropic等）のモデル改善や再学習に使用されることはありますか？",
    choices: ["はい、デフォルトで使用されます", "いいえ、Amazon Bedrockに入力されたデータがベースモデルの学習に使用されることはありません", "オプトアウトを申請した場合のみ使用されません", "AWSがデータをすべて公開します"],
    correct: 1,
    explanation: "AWSはBedrockに入力された顧客データをモデルの学習・改善に使用しないことを保証しています。これはエンタープライズ採用の重要な前提です。",
  },
  {
    id: 125, domain: "セキュリティ",
    question: "金融機関において、Amazon Bedrockへの通信をインターネットに公開せず、AWSのプライベートネットワーク内に閉じるために必要な構成要素は何ですか？",
    choices: ["インターネットゲートウェイ", "Interface VPC Endpoint (AWS PrivateLink)", "公開S3バケット", "SSHトンネル"],
    correct: 1,
    explanation: "AWS PrivateLinkのInterface VPC Endpointを使うと、インターネットを経由せずVPCからBedrockに安全に接続できます。",
  },
  {
    id: 126, domain: "セキュリティ",
    question: "特定のユーザーグループにのみ「Claude 3」の使用を許可し、他のモデルの使用を禁止したい場合、どのように制御しますか？",
    choices: ["全員を管理者にする", "IAMポリシーの Resource セクションで、特定のモデルARNへの bedrock:InvokeModel 権限のみを許可する", "モデルのパスワードを教えない", "物理的にアクセスを遮断する"],
    correct: 1,
    explanation: "IAMポリシーでモデルARNを指定してbedrock:InvokeModelを制限することで、特定のモデルへのアクセスを細かく制御できます。",
  },
  {
    id: 127, domain: "セキュリティ",
    question: "Amazon Bedrock Guardrailsを使用して、入力と出力の両方で「氏名」や「クレジットカード番号」を自動的に検出してマスクしたい場合、どの機能を使用しますか？",
    choices: ["Content filters", "Sensitive information filters (PII)", "Denied topics", "Word filters"],
    correct: 1,
    explanation: "Sensitive information filters（PIIフィルタ）は氏名・住所・電話番号・クレジットカード番号などを自動検出してマスクまたはブロックします。",
  },
  {
    id: 128, domain: "セキュリティ",
    question: "生成AIの利用状況を監査するために、誰がどのモデルに何を尋ねたかのログ（入出力の全文）を保存するBedrockの機能は何ですか？",
    choices: ["AWS CloudTrail (API実行履歴のみ)", "Model Invocation Logging", "Amazon Inspector", "AWS Artifact"],
    correct: 1,
    explanation: "Model Invocation LoggingはプロンプトとレスポンスをS3またはCloudWatch Logsに保存します。監査・デバッグ・品質管理に使用します。",
  },
  {
    id: 129, domain: "セキュリティ",
    question: "「責任あるAI（Responsible AI）」の5つの柱に含まれないものはどれですか？",
    choices: ["公平性 (Fairness)", "透明性 (Explainability)", "堅牢性 (Robustness)", "最大の利益 (Maximum Profit)"],
    correct: 3,
    explanation: "責任あるAIの柱は公平性・透明性・堅牢性・プライバシー・安全性です。「最大の利益」は含まれません。",
  },
  {
    id: 130, domain: "セキュリティ",
    question: "Amazon BedrockでAWS KMSを使用してデータを暗号化する際、カスタムキー（CMK）で暗号化できる対象はどれですか？",
    choices: ["基盤モデルの元の重み", "カスタムモデルの重み、知識ベースのデータソースのインデックス、モデル呼び出しログなど", "インターネット全体のデータ", "AWSの請求書"],
    correct: 1,
    explanation: "AWS KMSのCMKでカスタムモデル・知識ベースインデックス・呼び出しログを暗号化でき、鍵管理の完全な制御が可能になります。",
  },
  {
    id: 131, domain: "セキュリティ",
    question: "プロンプトインジェクションの対策として、システムプロンプトとユーザー入力を明確に区切るために使用される「###」や「---」などの記号を何と呼びますか？",
    choices: ["Token", "Delimiter (デリミタ/区切り文字)", "Stop sequence", "Mask"],
    correct: 1,
    explanation: "Delimiter（区切り文字）でシステムプロンプトとユーザー入力を明確に分離することで、インジェクション攻撃のリスクを低減できます。",
  },
  {
    id: 132, domain: "セキュリティ",
    question: "開発者が誤ってモデルに不適切なリクエストをした際、Guardrailsがそれをブロックしました。このブロックされたイベントのログはどこで確認できますか？",
    choices: ["Amazon S3 または CloudWatch Logs (ログ設定が有効な場合)", "AWS Trusted Advisor", "コンソールのベルマーク", "IAM ダッシュボード"],
    correct: 0,
    explanation: "GuardrailsのブロックイベントはModel Invocation Loggingを有効にしてS3またはCloudWatch Logsで記録・確認できます。",
  },
  {
    id: 133, domain: "セキュリティ",
    question: "Amazon Bedrockにおいて、モデルが生成する画像に目に見えない「透かし」を入れ、AI生成画像であることを識別可能にする技術は何と呼ばれますか？",
    choices: ["Encryption", "Digital Watermarking", "Steganography", "Image Masking"],
    correct: 1,
    explanation: "Digital Watermarkingは人間の目には見えない透かしをAI生成画像に埋め込みます。Titan画像生成モデルがこの機能をサポートしています。",
  },
  {
    id: 134, domain: "セキュリティ",
    question: "データの主権（Data Sovereignty）を確保するために、特定のリージョン（例：東京リージョン）内でのみデータを処理および保存するように設定することは重要ですか？",
    choices: ["いいえ、どこでも同じです", "はい、法的・規制上の要件を満たすために特定のリージョンを指定し、クロスリージョン推論を制限する必要があります", "はい、ただし料金が高くなります", "いいえ、AWSが勝手に決めます"],
    correct: 1,
    explanation: "GDPRや個人情報保護法などの規制要件を満たすために、データの処理・保存リージョンを明示的に制御することが重要です。",
  },
  {
    id: 135, domain: "セキュリティ",
    question: "Guardrailsの「しきい値」設定について、有害でない短い会話を過剰にブロックしないようにするには？",
    choices: ["しきい値を最大にする", "フィルタの感度を適切に調整し、有害でない短い会話を過剰にブロックしないようにテストと評価を繰り返す", "すべてをブロックする", "何もしない"],
    correct: 1,
    explanation: "Guardrailsのしきい値はユースケースに合わせて調整が必要です。過剰なブロックはUXを損ないます。継続的なテストと評価が重要です。",
  },
  {
    id: 136, domain: "セキュリティ",
    question: "Amazon Bedrockのモデルアクセス（Model Access）を管理できるのは、どのような権限を持つユーザーですか？",
    choices: ["すべてのユーザー", "適切なIAM権限（bedrock:GetModelInferencePolicy等）を持つ管理者", "モデルプロバイダー", "外部のハッカー"],
    correct: 1,
    explanation: "モデルアクセスの有効化・無効化には適切なIAM権限（bedrock:*）が必要です。最小権限の原則に従って管理者のみに付与します。",
  },
  {
    id: 137, domain: "セキュリティ",
    question: "AWS CloudTrailで記録されるBedrockのイベントには何が含まれますか？",
    choices: ["プロンプトの全文", "InvokeModel などのAPIが「誰によって、いつ、どのIPから」呼び出されたかという管理プレーンの履歴", "回答の全文", "モデルのパラメータ"],
    correct: 1,
    explanation: "CloudTrailはAPI操作の管理プレーンログ（誰が・いつ・どこから・何をしたか）を記録します。プロンプト内容はModel Invocation Loggingで記録します。",
  },
  {
    id: 138, domain: "セキュリティ",
    question: "生成AIのモデルが特定の集団（例：性別、人種）に対して不当な偏りがある回答をすることを防ぐ取り組みを何と呼びますか？",
    choices: ["Bias mitigation (バイアス軽減)", "Overfitting", "Underfitting", "Backpropagation"],
    correct: 0,
    explanation: "バイアス軽減はデータの多様性確保・公平性評価・GuardrailsによるフィルタリングなどでAIの差別的出力を防ぐ取り組みです。",
  },
  {
    id: 139, domain: "セキュリティ",
    question: "Amazon Bedrock Guardrailsを複数のアプリケーションで共通して使いたい場合、どうすればよいですか？",
    choices: ["毎回作り直す", "作成したGuardrailのIDを、各アプリケーションのAPI呼び出し時のパラメータとして指定する", "アプリケーションを1つにまとめる", "リージョンを1つにする"],
    correct: 1,
    explanation: "GuardrailはIDで識別されます。複数のアプリから同一のGuardrailを参照することで、一元管理とポリシーの一貫性が保てます。",
  },
  {
    id: 140, domain: "セキュリティ",
    question: "セキュリティ上の理由から、モデルが特定の競合他社について話すのを禁止したい場合、Guardrailsで設定すべき項目はどれですか？",
    choices: ["Content filters", "Denied topics", "PII filters", "Contextual grounding"],
    correct: 1,
    explanation: "Denied topicsは特定のトピック（競合他社・政治・法的アドバイス等）についてモデルが話すことを禁止する機能です。",
  },
  {
    id: 141, domain: "セキュリティ",
    question: "RAGシステムにおいて、検索されたドキュメントが「全くの無関係」である場合にモデルに無理やり答えさせないようにするための Guardrails の新しい機能は何ですか？",
    choices: ["PII Masking", "Contextual Grounding Check (コンテキストに基づいたグラウンディングチェック)", "Denied Topics", "Token Limit"],
    correct: 1,
    explanation: "Contextual Grounding Checkは回答が検索されたコンテキストに基づいているか、質問に関連しているかを確認し、ハルシネーションを防ぎます。",
  },
  {
    id: 142, domain: "セキュリティ",
    question: "AWSにおいて「責任共有モデル」に基づき、ユーザーが責任を負うのはどの部分ですか？",
    choices: ["基盤モデルのセキュリティ", "データセンターの物理的保護", "アプリケーションコード、データ、プロンプトの内容、IAMポリシーの設定", "モデルのトレーニングアルゴリズム"],
    correct: 2,
    explanation: "AWSはモデルとインフラのセキュリティを担当し、ユーザーはアプリコード・データ・プロンプト設計・IAM設定の責任を負います。",
  },
  {
    id: 143, domain: "セキュリティ",
    question: "特定の業界（医療など）の規制遵守（HIPAA等）のために、Amazon Bedrockを使用する前に確認すべきドキュメントは何ですか？",
    choices: ["AWS コンプライアンスレポート (Artifact) や各サービスのコンプライアンス対応状況", "昨日のニュース", "Wikipedia", "SNSの評判"],
    correct: 0,
    explanation: "AWS Artifactでコンプライアンスレポートを確認し、BedrockがHIPAA・GDPR等の規制に対応しているかを事前に検証することが必要です。",
  },
  {
    id: 144, domain: "セキュリティ",
    question: "プロンプトインジェクションによって、モデルが「エージェントに紐付けられた機密性の高いLambda関数」を不正に実行しようとするリスクへの対策はどれですか？",
    choices: ["Lambdaのコード内で入力パラメータの厳格なバリデーションとサニタイズを行う", "Lambdaを削除する", "エージェントの指示を短くする", "温度を0にする"],
    correct: 0,
    explanation: "Lambdaコード内での入力バリデーション・サニタイズは多層防御の重要な要素です。Guardrailsと組み合わせることでより強固な保護が実現できます。",
  },
  {
    id: 145, domain: "セキュリティ",
    question: "Amazon Bedrockの「Model invocation logging」で「テキスト、画像、音声データ」をすべてログに含める設定にした場合の懸念点は何ですか？",
    choices: ["ログが綺麗になる", "ログの保存容量が急速に増加し、S3のコストが増えるとともに、ログ内の機密情報の保護がより重要になる", "ログが見えなくなる", "何も起きない"],
    correct: 1,
    explanation: "フルロギングは完全な監査証跡を提供しますが、S3コストが増加し、ログ内のPII・機密情報の適切な保護（暗号化・アクセス制御）が必要です。",
  },
  {
    id: 146, domain: "セキュリティ",
    question: "モデルの出力の「正確性（Accuracy）」を確認するために、AIではなく人間が回答を検証し、フィードバックを行うプロセスを総称して何と呼びますか？",
    choices: ["Human-in-the-loop (HITL)", "Auto-correction", "Self-healing", "Over-the-air"],
    correct: 0,
    explanation: "Human-in-the-loop（HITL）は高リスクの判断や精度が重要なシナリオで人間がAIの出力を検証・修正するプロセスです。",
  },
  {
    id: 147, domain: "セキュリティ",
    question: "Bedrock Guardrailsを使用して特定の単語（不適切な言葉など）をブロックしたい場合、単語のリストを登録する機能を何と呼びますか？",
    choices: ["Word filters", "Sensitive information filters", "Denied topics", "Content filters"],
    correct: 0,
    explanation: "Word filtersは特定の単語・フレーズのリストを登録し、入出力でそれらが検出された場合にブロックまたはマスクします。",
  },
  {
    id: 148, domain: "セキュリティ",
    question: "Amazon Bedrock Knowledge BasesのデータソースとしてS3を使用する際、S3バケットへのアクセス権限をBedrockに与えるために必要なものは何ですか？",
    choices: ["S3をパブリックにする", "Bedrockのサービスプリンシパルを信頼し、S3への s3:GetObject 等の権限を持つ適切なIAMロールを作成し割り当てる", "rootユーザーでログインする", "バケット名を「bedrock-data」にする"],
    correct: 1,
    explanation: "Bedrockサービスプリンシパルを信頼するIAMロールにS3アクセス権限を付与することで、Bedrockがデータを安全に読み込めます。",
  },
  {
    id: 149, domain: "セキュリティ",
    question: "セキュリティのベストプラクティスとして、Bedrock APIを呼び出すIAMポリシーに Resource: \"*\" を使用することを避けるべきなのはなぜですか？",
    choices: ["動作しなくなるから", "最小権限の原則（Least Privilege）に従い、必要なモデルのみへのアクセスを許可してリスクを最小化するため", "料金が高くなるから", "AWSが推奨しているから"],
    correct: 1,
    explanation: "最小権限の原則に従い、必要なモデルARNのみを明示的に指定することで、不要なモデルへのアクセスリスクを排除します。",
  },
  {
    id: 150, domain: "セキュリティ",
    question: "生成AIを安全に利用し続けるための「継続的なモニタリング」において、監視すべき対象に含まれないものはどれですか？",
    choices: ["モデルの推論エラー率", "ユーザーからの不適切コンテンツの報告", "開発者のタイピング速度", "Guardrailsによるブロック率"],
    correct: 2,
    explanation: "継続的モニタリングの対象はエラー率・ブロック率・ユーザーフィードバック・コスト・レイテンシなどです。タイピング速度は関係ありません。",
  },
];
